image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 677.07759,    0.     ,  311.79159,
            0.     ,  679.28141,  298.1121 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.160585, -0.012919, 0.000601, -0.000946, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 649.0752 ,    0.     ,  310.04422,    0.     ,
            0.     ,  660.27753,  300.16012,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]